# Creation of NumPy Arrays

## Different Methods for numpy.array creation:
- `np.array()`: Converts a Python list or tuple to a NumPy array.
- `np.zeros()`: Creates an array of zeros with the specified shape.
- `np.ones()`: Creates an array of ones with the specified shape.
- `np.full()`: Creates an array filled with a specific value.
- `np.arange()`: Generates an array of values within a specified range, with a specified step size.
- `np.linspace()`: Generates a specified number of equally spaced values over a given interval.
- `np.random.rand()`: Generates random numbers from a uniform distribution between 0 and 1.
- `np.random.randn()`: Generates random numbers from a standard normal distribution.
- `np.random.randint()`: Generates random integers within a given range.
- `np.eye()`: Creates an identity matrix (diagonal of ones, with zeros elsewhere).
- `np.diag()`: Creates a diagonal matrix with specified values along the diagonal.

In [10]:
import numpy as np

# 1. Using np.array() for converting Python list or tuple to NumPy array

# 1a -> From Python List
py_list = [1, 2, 3, 4, 5]
arr_from_list = np.array(py_list)
print("Array from list:", arr_from_list)

# 1b -> From Python tuple
py_tuple = (1, 2, 3, 4, 5)
arr_from_tuple = np.array(py_tuple)
print("Array from tuple:", arr_from_tuple)

# 2. Using np.zeros() to create an array filled with zeros
arr_zeros = np.zeros((3, 4))  # 3x4 matrix
print("Array of zeros:\n", arr_zeros)

# 3. Using np.ones() to create an array filled with ones
arr_ones = np.ones((2, 5))  # 2x5 matrix
print("Array of ones:\n", arr_ones)

# 4. Using np.full() to create an array filled with a specific value
arr_full = np.full((3, 3), 7)  # 3x3 matrix, all elements are 7
print("Array filled with 7:\n", arr_full)

# 5. Using np.arange() to create an array with a range of values
arr_arange = np.arange(0, 10, 2)  # Values from 0 to 10 with step 2
print("Array using arange:", arr_arange)

# 6. Using np.linspace() to create an array of equally spaced values
arr_linspace = np.linspace(0, 1, 5)  # 5 equally spaced numbers between 0 and 1
print("Array using linspace:", arr_linspace)

# 7. Using np.random.rand() to create an array of random numbers between 0 and 1
arr_rand = np.random.rand(2, 3)  # 2x3 array with random values
print("Array of random values (uniform):\n", arr_rand)

# 8. Using np.random.randn() to create an array of random numbers from a standard normal distribution
arr_randn = np.random.randn(2, 3)  # 2x3 array with values from standard normal distribution
print("Array of random values (normal):\n", arr_randn)

# 9. Using np.random.randint() to create an array of random integers within a specified range
arr_randint = np.random.randint(1, 10, size=(3, 3))  # 3x3 array with random integers between 1 and 10
print("Array of random integers:\n", arr_randint)

# 10. Using np.eye() to create an identity matrix
arr_eye = np.eye(3)  # 3x3 identity matrix
print("Identity matrix:\n", arr_eye)

# 11. Using np.diag() to create a diagonal matrix
arr_diag = np.diag([1, 2, 3])  # Diagonal matrix with values 1, 2, 3 along the diagonal
print("Diagonal matrix:\n", arr_diag)

Array from list: [1 2 3 4 5]
Array from tuple: [1 2 3 4 5]
Array of zeros:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Array of ones:
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
Array filled with 7:
 [[7 7 7]
 [7 7 7]
 [7 7 7]]
Array using arange: [0 2 4 6 8]
Array using linspace: [0.   0.25 0.5  0.75 1.  ]
Array of random values (uniform):
 [[0.02604647 0.78790299 0.06238692]
 [0.8215219  0.75438649 0.85496081]]
Array of random values (normal):
 [[-1.90570442 -2.4337004   0.13568554]
 [ 0.58798882 -0.52042586  0.42270448]]
Array of random integers:
 [[6 4 2]
 [7 2 9]
 [5 8 4]]
Identity matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Diagonal matrix:
 [[1 0 0]
 [0 2 0]
 [0 0 3]]
