# Operations on Numpy Arrays

## 1. Arithmetic Operations

In [1]:
import numpy as np

# Create two arrays
a = np.array([1, 2, 3, 4, 5])
b = np.array([5, 4, 3, 2, 1])

# Addition
add_result = a + b  # Output: [6, 6, 6, 6, 6]
print("Addition:", add_result)

# Subtraction
sub_result = a - b  # Output: [-4, -2, 0, 2, 4]
print("Subtraction:", sub_result)

# Multiplication
mul_result = a * b  # Output: [5, 8, 9, 8, 5]
print("Multiplication:", mul_result)

# Division
div_result = a / b  # Output: [0.2, 0.5, 1.0, 2.0, 5.0]
print("Division:", div_result)

# Modulo
mod_result = a % b  # Output: [1, 2, 0, 0, 0]
print("Modulo:", mod_result)

# Exponentiation
exp_result = a ** 2  # Output: [ 1, 4, 9, 16, 25]
print("Exponentiation:", exp_result)

# Matrix multiplication (Dot product)
mat_mul_result = np.dot(a, b)  # Output: 35 (1*5 + 2*4 + 3*3 + 4*2 + 5*1)
print("Matrix multiplication (Dot product):", mat_mul_result)

# Trigonometric functions (example using sine)
sin_result = np.sin(a)  # Sine of each element
print("Sine of array:", sin_result)

# Converting degree values to radians
degrees = np.array([0, 30, 45, 60, 90])
radians = np.radians(degrees)  # Convert degrees to radians
print("Radians:", radians)

# Logarithmic functions (example using natural log)
log_result = np.log(a)  # Natural logarithm of each element
print("Natural Logarithm:", log_result)

# Bitwise operations (example using AND)
bitwise_and_result = a & 2  # Bitwise AND of each element with 2
print("Bitwise AND with 2:", bitwise_and_result)

# Bitwise operations (example using OR)
bitwise_or_result = a | 2  # Bitwise OR of each element with 2
print("Bitwise OR with 2:", bitwise_or_result)

Addition: [6 6 6 6 6]
Subtraction: [-4 -2  0  2  4]
Multiplication: [5 8 9 8 5]
Division: [0.2 0.5 1.  2.  5. ]
Modulo: [1 2 0 0 0]
Exponentiation: [ 1  4  9 16 25]
Matrix multiplication (Dot product): 35
Sine of array: [ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
Radians: [0.         0.52359878 0.78539816 1.04719755 1.57079633]
Natural Logarithm: [0.         0.69314718 1.09861229 1.38629436 1.60943791]
Bitwise AND with 2: [0 2 2 0 0]
Bitwise OR with 2: [3 2 3 6 7]


## 2. Comparison Operations
- These operations compare elements in the arrays a and b, returning a boolean array.

In [2]:
import numpy as np

# Create arrays
a = np.array([1, 2, 3, 4, 5])
b = np.array([5, 4, 3, 2, 1])

# Equality comparison
print(a == b)  # Output: [False False  True False False]

# Greater than comparison
print(a > b)   # Output: [False False False  True  True]

# Less than comparison
print(a < b)   # Output: [ True  True False False False]

# Not equal comparison
print(a != b)  # Output: [ True  True False  True  True]

# Greater than or equal comparison
print(a >= b)  # Output: [False False  True  True  True]

# Less than or equal comparison
print(a <= b)  # Output: [ True  True  True False False]

[False False  True False False]
[False False False  True  True]
[ True  True False False False]
[ True  True False  True  True]
[False False  True  True  True]
[ True  True  True False False]


## 3. Aggregation Functions
- These functions compute summary statistics over the array.

In [4]:
import numpy as np

# Create arrays
a = np.array([1, 2, 3, 4, 5])
b = np.array([5, 4, 3, 2, 1])

# Sum
print(np.sum(a))  # Output: 15

# Mean
print(np.mean(a))  # Output: 3.0

# Median
print(np.median(a))  # Output: 3.0

# Standard deviation
print(np.std(a))  # Output: 1.4142135623730951

# Variance
print(np.var(a))  # Output: 2.0

# Maximum
print(np.amax(a))  # Output: 5

# Minimum
print(np.amin(a))  # Output: 1

15
3.0
3.0
1.4142135623730951
2.0
5
1


## 4. Sorting Operations

In [5]:
import numpy as np

# Create an array
a = np.array([5, 2, 9, 1, 5, 6])

# Sort the array (default is ascending order)
sorted_a = np.sort(a)  
print("Sorted Array (Ascending):", sorted_a)

# Reverse sort the array (sort in descending order)
reverse_sorted_a = np.sort(a)[::-1]  
print("Reverse Sorted Array (Descending):", reverse_sorted_a)

Sorted Array (Ascending): [1 2 5 5 6 9]
Reverse Sorted Array (Descending): [9 6 5 5 2 1]


## 5. Transpose Operations

In [7]:
import numpy as np

# 1D Array Transpose
a = np.array([1, 2, 3])
print("Original 1D Array:", a)
print("Transposed 1D Array:", a.T)  # Transpose has no effect on 1D array

# 2D Array Transpose
b = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("\nOriginal 2D Array:\n", b)
print("Transposed 2D Array:\n", b.T)

# 3D Array Transpose
c = np.random.rand(2, 3, 4)  # 3D array of shape (2, 3, 4)
print("\nOriginal 3D Array Shape:", c.shape)
print("Transposed 3D Array Shape:", c.transpose(1, 0, 2).shape)  # Swapping axes

Original 1D Array: [1 2 3]
Transposed 1D Array: [1 2 3]

Original 2D Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Transposed 2D Array:
 [[1 4 7]
 [2 5 8]
 [3 6 9]]

Original 3D Array Shape: (2, 3, 4)
Transposed 3D Array Shape: (3, 2, 4)


# How do you know the shape and size of an array?

- ndarray.ndim will tell you the number of axes, or dimensions, of the array.

- ndarray.size will tell you the total number of elements of the array. This is the product of the elements of the array’s shape.

- ndarray.shape will display a tuple of integers that indicate the number of elements stored along each dimension of the array. If, for example, you have a 2-D array with 2 rows and 3 columns, the shape of your array is (2, 3)

In [8]:
import numpy as np

# 1D Array
a = np.array([1, 2, 3, 4, 5])
print("1D Array:")
print("Array:", a)
print("Number of Dimensions (ndim):", a.ndim)
print("Shape:", a.shape)
print("Size (Total number of elements):", a.size)
print()

# 2D Array
b = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("2D Array:")
print("Array:\n", b)
print("Number of Dimensions (ndim):", b.ndim)
print("Shape:", b.shape)  # Tuple (rows, columns)
print("Size (Total number of elements):", b.size)
print()

# 3D Array
c = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print("3D Array:")
print("Array:\n", c)
print("Number of Dimensions (ndim):", c.ndim)
print("Shape:", c.shape)  # Tuple (depth, rows, columns)
print("Size (Total number of elements):", c.size)
print()

# 4D Array
d = np.array([[[[1, 2], [3, 4]], [[5, 6], [7, 8]]], [[[9, 10], [11, 12]], [[13, 14], [15, 16]]]])
print("4D Array:")
print("Array:\n", d)
print("Number of Dimensions (ndim):", d.ndim)
print("Shape:", d.shape)  # Tuple (batch, depth, rows, columns)
print("Size (Total number of elements):", d.size)

1D Array:
Array: [1 2 3 4 5]
Number of Dimensions (ndim): 1
Shape: (5,)
Size (Total number of elements): 5

2D Array:
Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Number of Dimensions (ndim): 2
Shape: (3, 3)
Size (Total number of elements): 9

3D Array:
Array:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
Number of Dimensions (ndim): 3
Shape: (2, 2, 2)
Size (Total number of elements): 8

4D Array:
Array:
 [[[[ 1  2]
   [ 3  4]]

  [[ 5  6]
   [ 7  8]]]


 [[[ 9 10]
   [11 12]]

  [[13 14]
   [15 16]]]]
Number of Dimensions (ndim): 4
Shape: (2, 2, 2, 2)
Size (Total number of elements): 16
