# Indexing

You can index and slice NumPy arrays in the same ways you can slice Python lists.



In [2]:
import numpy as np

# 1D Array Indexing
a = np.array([10, 20, 30, 40, 50])
print("1D Array:", a)

# Indexing (Accessing individual elements)
print("Element at index 0:", a[0])  # Output: 10
print("Element at index -1 (last element):", a[-1])  # Output: 50

# 2D Array Indexing
b = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("\n2D Array:\n", b)

# Indexing (Accessing individual elements)
print("Element at (0, 1):", b[0][1])  # or b[0, 1]
print("Element at (2, 2):", b[2][2])  # or b[2, 2]

# 3D Array Indexing
c = np.random.rand(4, 3, 2)
print("\n3D Array:\n", c)

# Accessing an element from 3D array
print("Element at (1, 2, 0):", c[1][2][0]) # or c[1, 2, 0]

1D Array: [10 20 30 40 50]
Element at index 0: 10
Element at index -1 (last element): 50

2D Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Element at (0, 1): 2
Element at (2, 2): 9

3D Array:
 [[[0.84762623 0.18695667]
  [0.38701642 0.71183914]
  [0.95990061 0.04915228]]

 [[0.72327575 0.18360268]
  [0.5435994  0.44760271]
  [0.26863486 0.25168978]]

 [[0.99199005 0.65889309]
  [0.33225924 0.53555656]
  [0.86475468 0.78940708]]

 [[0.20543696 0.4685444 ]
  [0.24735494 0.13769639]
  [0.72835968 0.70598264]]]
Element at (1, 2, 0): 0.26863485880913296


## Boolean Indexing

In [4]:
import numpy as np

# Create a NumPy array
a = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])
print("Original Array:", a)

# Boolean indexing to select elements greater than 50
print("\nElements greater than 50:", a[a > 50])

# Boolean indexing to select even elements
print("\nEven elements:", a[a % 2 == 0])

# Using boolean indexing to filter elements based on multiple conditions
print("\nElements greater than 30 and divisible by 10:", a[(a > 30) & (a % 10 == 0)])

# Boolean indexing in 2D arrays
b = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("\nOriginal 2D Array:\n", b)

# Select elements greater than 5 in the 2D array
print("\nElements greater than 5 in 2D array:\n", b[b > 5])

Original Array: [ 10  20  30  40  50  60  70  80  90 100]

Elements greater than 50: [ 60  70  80  90 100]

Even elements: [ 10  20  30  40  50  60  70  80  90 100]

Elements greater than 30 and divisible by 10: [ 40  50  60  70  80  90 100]

Original 2D Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Elements greater than 5 in 2D array:
 [6 7 8 9]


# Slicing

In [3]:
import numpy as np

# 1D Array Slicing
a = np.array([10, 20, 30, 40, 50])
print("1D Array:", a)

# Slicing (Selecting elements in a range)
print("Sliced array from index 1 to 3:", a[1:4])  # Output: [20 30 40]

# Slicing with step
print("Sliced array with step 2:", a[::2])  # Output: [10 30 50]

# 2D Array Slicing
b = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("\n2D Array:\n", b)

# Slicing (Selecting entire rows or columns)
print("First row:", b[0])  # Output: [1 2 3]
print("First column:", b[:, 0])  # Output: [1 4 7]

# Slicing (Selecting subarrays from specific rows and columns)
print("Subarray (first two rows, first two columns):\n", b[:2, :2])  # Output: [[1 2] [4 5]]

# 3D Array Slicing
c = np.random.rand(4, 3, 2)
print("\n3D Array:\n", c)

# Slicing (Selecting a slice of 2D array from the 3D array)
print("Sliced 2D array from the first slice of 3D array:\n", c[0, :, :])

1D Array: [10 20 30 40 50]
Sliced array from index 1 to 3: [20 30 40]
Sliced array with step 2: [10 30 50]

2D Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
First row: [1 2 3]
First column: [1 4 7]
Subarray (first two rows, first two columns):
 [[1 2]
 [4 5]]

3D Array:
 [[[0.84129546 0.15792064]
  [0.00760944 0.37515335]
  [0.13070929 0.75691941]]

 [[0.6584012  0.80922337]
  [0.72823822 0.8045272 ]
  [0.98938731 0.44417847]]

 [[0.31460976 0.45491058]
  [0.80600634 0.79100879]
  [0.46138737 0.11486606]]

 [[0.15490062 0.48140201]
  [0.38692375 0.74922459]
  [0.47498407 0.10077133]]]
Sliced 2D array from the first slice of 3D array:
 [[0.84129546 0.15792064]
 [0.00760944 0.37515335]
 [0.13070929 0.75691941]]
