# 1. Reshaping
Reshaping allows you to change the shape of an array without modifying its data. This is useful when you want to organize the data in a specific way, for example, changing a flat array into a matrix.

-> Key Points:
- The total number of elements in the reshaped array must match the total number of elements in the original array. In the above examples, the total size is 12.
- reshape() doesn't modify the original array; instead, it returns a new view of the array with the desired shape.

In [1]:
import numpy as np

# Original 1D array
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
print("Original 1D Array:", a)

# Reshape it into a 2D array with 3 rows and 4 columns
reshaped_a = a.reshape(3, 4)
print("Reshaped to 3x4 Array:\n", reshaped_a)

# Reshape into a 2D array with 4 rows and 3 columns
reshaped_b = a.reshape(4, 3)
print("Reshaped to 4x3 Array:\n", reshaped_b)

# Reshape into a 3D array with 2 matrices, each having 2 rows and 3 columns
reshaped_c = a.reshape(2, 2, 3)
print("Reshaped to 2x2x3 Array:\n", reshaped_c)

Original 1D Array: [ 1  2  3  4  5  6  7  8  9 10 11 12]
Reshaped to 3x4 Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Reshaped to 4x3 Array:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
Reshaped to 2x2x3 Array:
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


## Simple 1D to 2D Reshaping

In [1]:
import numpy as np

# Original 1D array
a = np.array([1, 2, 3, 4, 5, 6])

# Reshape into 1 row and automatically calculate the number of columns
reshaped = a.reshape(1, -1)

print("Reshaped Array (1 row, 6 columns):")
print(reshaped)

Reshaped Array (1 row, 6 columns):
[[1 2 3 4 5 6]]


## Reshaping a 1D Array to Multiple Rows

In [12]:
# Reshape into 2 rows and automatically calculate the number of columns
a = np.array([1, 2, 3, 4, 5, 6])
reshaped_multi_row = a.reshape(2, -1)

print("Reshaped Array (2 rows, 3 columns):")
print(reshaped_multi_row)

Reshaped Array (2 rows, 3 columns):
[[1 2 3]
 [4 5 6]]


## Simple 1D to 2D Reshaping for Columns

In [13]:
import numpy as np

# Original 1D array
a = np.array([1, 2, 3, 4, 5, 6])

# Reshape into 1 column and automatically calculate the number of rows
reshaped_col = a.reshape(-1, 1)

print("Reshaped Array (6 rows, 1 column):")
print(reshaped_col)

Reshaped Array (6 rows, 1 column):
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


## Reshaping a 1D Array into Multiple Columns (More than 1)

In [14]:
# Reshape into 2 columns and automatically calculate the number of rows
a = np.array([1, 2, 3, 4, 5, 6])
reshaped_2col = a.reshape(-1, 2)

print("Reshaped Array (3 rows, 2 columns):")
print(reshaped_2col)

Reshaped Array (3 rows, 2 columns):
[[1 2]
 [3 4]
 [5 6]]


# 2. Splitting
Splitting refers to dividing an array into smaller arrays. You can split arrays along specific axes.

-> Key Points:
- np.split() splits the array into equal-sized sub-arrays along a given axis.
- For 1D arrays, you can split them into several sub-arrays. For 2D arrays, you can split them along rows or columns.
- The sum of the sizes of the split arrays will always equal the size of the original array.

In [2]:
# Original 1D array
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

# Split the array into 3 sub-arrays
split_a = np.split(a, 3)
print("Split into 3 sub-arrays:", split_a)

# Split 2D array along rows
b = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
split_b = np.split(b, 2, axis=0)  # Splitting along rows (axis 0)
print("\nSplit 2D array along rows:\n", split_b)

# Split 2D array along columns
split_b_cols = np.split(b, 3, axis=1)  # Splitting along columns (axis 1)
print("\nSplit 2D array along columns:\n", split_b_cols)

Split into 3 sub-arrays: [array([1, 2, 3, 4]), array([5, 6, 7, 8]), array([ 9, 10, 11, 12])]

Split 2D array along rows:
 [array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]])]

Split 2D array along columns:
 [array([[ 1],
       [ 4],
       [ 7],
       [10]]), array([[ 2],
       [ 5],
       [ 8],
       [11]]), array([[ 3],
       [ 6],
       [ 9],
       [12]])]


# 3. Stacking
Stacking combines multiple arrays into a single array along a new axis. There are different ways to stack arrays:

## 1. Vertical Stacking (vstack): Stacks arrays vertically (along rows).

In [3]:
# Original arrays
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Stack vertically
vstacked = np.vstack((a, b))
print("Vertically Stacked Array:\n", vstacked)

Vertically Stacked Array:
 [[1 2 3]
 [4 5 6]]


## 2. Horizontal Stacking (hstack): Stacks arrays horizontally (along columns).

In [4]:
# Stack horizontally
hstacked = np.hstack((a, b))
print("Horizontally Stacked Array:", hstacked)

Horizontally Stacked Array: [1 2 3 4 5 6]


## 3. Depth Stacking (dstack): Stacks arrays along the third dimension (depth).

In [6]:
# Stack along depth (3rd dimension)
dstacked = np.dstack((a, b))
print("Depth Stacked Array:\n", dstacked)

Depth Stacked Array:
 [[[1 4]
  [2 5]
  [3 6]]]


## 4. Concatenate: You can also use np.concatenate() to stack arrays along a specified axis.
-> How Concatenation Works:
- Axis 0 (Rows): When concatenating along axis 0, the arrays are stacked row-wise, meaning they are joined along the rows (vertical stacking).
- Axis 1 (Columns): When concatenating along axis 1, the arrays are stacked column-wise, meaning they are joined along the columns (horizontal stacking).

In [8]:
import numpy as np

# Define two 1D arrays
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Reshape both arrays into 2D arrays (1 row, 3 columns)
a_reshaped = a.reshape(1, -1)  # shape (1, 3)
b_reshaped = b.reshape(1, -1)  # shape (1, 3)

# Concatenate along axis 0 (rows)
# This will stack the arrays vertically, i.e., add rows to the 2D array
concatenated_rows = np.concatenate((a_reshaped, b_reshaped), axis=0)
print("Concatenated Array along rows:\n", concatenated_rows)

# Reshape a and b to column vectors (3 rows, 1 column)
a_col = a.reshape(-1, 1)  # shape (3, 1)
b_col = b.reshape(-1, 1)  # shape (3, 1)

# Concatenate along axis 1 (columns)
# This will stack the arrays horizontally, i.e., add columns to the 2D array
concatenated_cols = np.concatenate((a_col, b_col), axis=1)
print("Concatenated Array along columns:\n", concatenated_cols)

Concatenated Array along rows:
 [[1 2 3]
 [4 5 6]]
Concatenated Array along columns:
 [[1 4]
 [2 5]
 [3 6]]
