# Broadcasting

- Broadcasting is a feature in the NumPy library in Python that allows for arithmetic operations between arrays of different shapes.
- Broadcasting solves the problem of compatibility in shape between arrays of Afferg 00 lon uhing arithmetic operations.
- The smaller array is broadcasted across the larger array so that they have compatible shapes.
- Broadcasting provides a means of vectorizing array operations so that looping occurs in C instead of Python.

<img src="./images/broadcasting.png">

In [1]:
import numpy as np

# Example 1: Adding a scalar to an array
arr1 = np.array([[1, 2], [3, 4]])  # Shape (2, 2)
scalar = 5
result1 = arr1 + scalar

# Example 2: Adding two arrays with compatible shapes
arr2 = np.array([1, 0])            # Shape (2,)
result2 = arr1 + arr2               # Broadcasting arr2 across arr1

# Example 3: Multiplying a 2D array by a 1D array (with broadcasting)
arr3 = np.array([1, 2])            # Shape (2,)
result3 = arr1 * arr3               # Broadcasting arr3 across arr1

# Example 4: Broadcasting to a larger array shape
arr4 = np.array([1, 2])            # Shape (2,)
arr5 = np.array([[1, 2], [3, 4], [5, 6]])  # Shape (3, 2)
result4 = arr5 + arr4               # Broadcasting arr4 across arr5

# Example 5: Broadcasting a smaller array to a larger shape
arr6 = np.array([1])               # Shape (1,)
arr7 = np.array([[1, 2, 3], [4, 5, 6]])  # Shape (2, 3)
result5 = arr7 + arr6               # Broadcasting arr6 across arr7

# Printing results
print("Example 1 (Scalar addition):")
print(result1)

print("\nExample 2 (Array addition):")
print(result2)

print("\nExample 3 (Array multiplication):")
print(result3)

print("\nExample 4 (Broadcasting to larger shape):")
print(result4)

print("\nExample 5 (Broadcasting smaller array to larger shape):")
print(result5)

The history saving thread hit an unexpected error (OperationalError('attempt to write a readonly database')).History will not be written to the database.
Example 1 (Scalar addition):
[[6 7]
 [8 9]]

Example 2 (Array addition):
[[2 2]
 [4 4]]

Example 3 (Array multiplication):
[[1 4]
 [3 8]]

Example 4 (Broadcasting to larger shape):
[[2 4]
 [4 6]
 [6 8]]

Example 5 (Broadcasting smaller array to larger shape):
[[2 3 4]
 [5 6 7]]
